name: Testing web_rtc
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up cargo cache
      uses: actions/cache@v4
      continue-on-error: false
      with:
        path: |
          target-common
          .devbox
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-build-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          cargo-build

    - name: Install devbox
      uses: jetify-com/devbox-install-action@v0.12.0
      with:
        enable-cache: 'true'

    - name: Run cargo_build
      run: devbox run -- make cargo_build

  cargo_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main

    - name: Set up cargo cache
      uses: actions/cache@v4
      continue-on-error: false
      with:
        path: |
          target-common
          .devbox
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-test-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          cargo-test
          cargo-build

    - name: Install devbox
      uses: jetify-com/devbox-install-action@v0.12.0
      with:
        enable-cache: 'true'

    - name: Run cargo_test
      run: devbox run -- make cargo_test

    - name: Test publishing
      run: devbox run -- make publish_dry

  make_test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up cargo cache
      uses: actions/cache@v4
      continue-on-error: false
      with:
        path: |
          target-common
          .devbox
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
        key: cargo-make_test-${{ hashFiles('**/Cargo.lock') }}-${{ hashFiles('**/Cargo.toml') }}
        restore-keys: |
          cargo-make_test
          cargo-build

    - name: Install devbox
      uses: jetify-com/devbox-install-action@v0.12.0
      with:
        enable-cache: 'true'

    - name: Run make_test
      run: devbox run -- make make_test || true
